### ISSUE TITLE
dev to 99-02 mileage

### ISSUE THREAD

**Issue by joltshock** [mikebb203/IPC-Hammer#3]
So far using the OBDLink LX via bluetooth on COM4 works flawlessly. Thanks! 
Any plans for 99-02 mileage correction?

**Comment by mikebb203** [comment]
Yes.

**Comment by superdave0711** [comment]
-when do you thin the  milage correction will be avaible

**Comment by mikebb203** [comment]
I'm not sure. But I don't think it will be much longer.

**Comment by Myelectrogeek** [comment]
Following

**Comment by superdave0711** [comment]
is the millage correction available fo r99-02?

**Comment by johnsilverado** [comment]
Any updates on the 99-02 mileage correction?

**Comment by jsncook** [comment]
If you need any 99-02 bins, please let me know.  I have all the bins/util files that were available before 2008ish ;)

**Comment by mikebb203** [comment]
Interesting
