### ISSUE TITLE
Set hours?

### ISSUE THREAD

**Issue by IronDuke123** [mikebb203/IPC-Hammer#4]
Any chance of being able to set hours?  Could come in handy..
One of the guys here ordered a replacement IPC while I was out, it showed up programmed with mileage but zero hours..
Can't get IPC setup to run within sps2 because it's not a 'new' IPC..  radio/ipc place is supposed to either program mileage AND hours or leave them blank and let us..
I was able to be the hero though by zeroing mileage and then trying setup again, it ran!! I then was able to program mileage and hours and then continue programming as usual.. Yipee!!!

**Comment by mikebb203** [comment]
I plan to add it. Is tis2000 ipc replace supposed to do mileage and hours. I tried it once and it didn't seem to work right for me. I need to get a snoop of the hours change in order to add it.

**Comment by IronDuke123** [comment]
I almost logged the procedure this time, guess I should have..  Yes, when we order a cluster we have the option of having mileage and hours set or they leave it blank(at zero for both) and we perform the ipc setup prior to ipc programming.. When you run setup it checks to make sure it's a new ipc then you'll get a popup for mileage and hours.. Once it writes it has you turn the ign off and then on again and your good to go..  I can try and get a log this weekend if you no longer have access..  I can zero the mileage on my bench ipc but I can't zero the hours so I'm not 100% sure I can fake  the session..

**Comment by mikebb203** [comment]
I'll have to try that again.

**Comment by mikebb203** [comment]
Thanks for the tip on where to get the command to change hours. Hours should be in the next update.

**Comment by mikebb203** [comment]
Now in the program.
