### ISSUE TITLE
03 cluster no response after writing Cal.

### ISSUE THREAD

**Issue by PAVEDwithBRICKS** [mikebb203/IPC-Hammer#6]
Cluster won't power up after writing cal. 
Any way to force recovery?
OBDX Pro

**Comment by PAVEDwithBRICKS** [comment]
using newest 16.4

**Comment by mikebb203** [comment]
Sometimes depending on what went wrong you can try flashing again. But most of the time it won't work. You will need to use minimon from Infineon to reprogram it. Fixed until broken on YouTube has some videos on using minimon to reprogram.
