### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by Pako11T** [mikebb203/IPC-Hammer#8]
Just downloaded new update version but it wont let write ipc calibration  
All I get it try again with less important ipc ? 
I want to modified the cluster for 7k RPM 140MPH

**Comment by mikebb203** [comment]
You answered the question wrong. You need to answer No it's not going to make your life difficult.

**Comment by Pako11T** [comment]
Got it thank yoi.  How can i tell what bin has options for controls on steering wheel i need to program a cluster but need controls on steering wheel

**Comment by Pako11T** [comment]
?

**Comment by mikebb203** [comment]
Find a vin for a truck that has the options you want and use tis2web.service.gm.com to find the calibration number for the cluster you're using.
